services:
  slack-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: slack-ai-bot
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
      - LOG_LEVEL=INFO
    env_file:
      - ../.env
    volumes:
      - ../app:/app/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - slack-bot-network

  redis:
    image: redis:7-alpine
    container_name: slack-bot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - slack-bot-network
    profiles:
      - redis

volumes:
  redis_data:

networks:
  slack-bot-network:
    driver: bridge
